### ISSUE TITLE
Multiple modals opened bug

### ISSUE THREAD

**Issue by jagabs** [GreenFlag31/modal-library#2]
![Screenshot 2024-02-29 at 10 59 35 PM](https://github.com/GreenFlag31/modal-library/assets/17292042/fcb598a8-ec20-4def-9fc5-b0e1708f6d77)

the modal acts weird when I open 14-15 modals. 

I know its unwise but its worth testing hehe

**Comment by GreenFlag31** [comment]
Some serious stacked content here 😂

Yes, stacking 15 modals is very uncommon in terms of UI/UX experience. What do you mean precisely by 'acting weird'? Lags? Do you have any errors in the console?

**Comment by jagabs** [comment]
wahaha yea am trying to replicate the instagram in web where you open a persons profile then click a photo then click another profile. when you back it, the history is somewhat preserved? 

but the bug is the modal contents on the 14th 15th modal is distorted

**Comment by GreenFlag31** [comment]
Hi,

I have made a test with 15+ modals opened and did not find any bug. What do you mean exactly with 'the modal content is distorted'? This looks like a CSS problem (the modal content is on your side) and is unlikely to be linked with the library.

* Do you have any view encapsulation turned off in a component that could create style collision?
* Have you tried to restart the development server?
* Do you have any error in the console?
* Did you inspect the CSS in your browser to see where was the problem?
* Are you stacking the same components or different ones?

If the issue persists feel free to open a stackblitz or a github repo, so I can check where is the problem.

**Comment by jagabs** [comment]
> Do you have any view encapsulation turned off in a component that could create style collision?

Nope

> Have you tried to restart the development server?

Yes

> Do you have any error in the console?

No error

>Did you inspect the CSS in your browser to see where was the problem?

Im not sure if its a css problem, cos even when i change z-index: 99999999 still not visible.

>Are you stacking the same components or different ones?
lets say i have 3 unique components and i stack it like 1, 2, 3, 2, 1, 2, 3, 1, 2, 3

This is how it looks when it gets bugged

<img width="677" alt="Screenshot 2024-03-01 at 8 43 37 PM" src="https://github.com/GreenFlag31/modal-library/assets/17292042/f161f8c8-61d9-4f70-9543-ef3f5e255d40">

This is the correct view
<img width="1175" alt="Screenshot 2024-03-01 at 8 45 36 PM" src="https://github.com/GreenFlag31/modal-library/assets/17292042/e1c5b500-e21a-44ea-90fc-9a83cad5c9d9">

**Comment by GreenFlag31** [comment]
Are you setting the modal 'full screen' like it is a new page where you navigate to? Or modals stay for what they were made for, modals? 

The non working version (first image) has a different title, 'test'. Are you sure that it's not a different component?

I don't think I will be able to reproduce the error on my side, since I don't have any errors, I would need the full picture of what you are precisely doing. Could you open a github repo, so that I can check what is not working?

**Comment by jagabs** [comment]
setting it as fullscreen as width and height 100%. so just modal z-1000 then z-2000 and so on. It works well for the first few modals

> The non working version (first image) has a different title, 'test'. Are you sure that it's not a different component?

This is the same component but i fetched it in db.

**Comment by GreenFlag31** [comment]
Well, it's complicated for me to identify the bug without reproduction possibility. But if you fetch it in DB, it means that this is an asynchronous operation, so maybe the modal is instantiated before the content is available, rendering no content. Try to 'turn off' the fetching in DB and load static data to see if it's the case. There must be a problem with the way you are rendering this component, there is no reason why the first 13 modals would instantiate normally.

**Comment by jagabs** [comment]
still doesn't work, i noticed tho when i reach around 17 - 18 modals it starts distorting but when i try to add display none to the first one it is fixed then i open another one then its distorted again then i try to add display none to the second modal and so on and so forth

**Comment by jagabs** [comment]
i think i know the problem, its the multiple overlays that distorts the screen :)

**Comment by GreenFlag31** [comment]
It's not really the intend of modals to be opened like you are navigating to a new component. I would suggest to do it the regular way, through navigation via the Angular API (Routes interface).

But normally, the new modals to be opened should always be upfront with the previous modal or current background. I don't get how applying 'display:none' to the first modal solves the problem, since the first modal has a z-index of 1000 while the 18th modal has a z-index of 18 000. Why was it at 14-15, and now 17-18 ? I don't get it. There must be a CSS styles overload on your component that interferes with the modal. I've tested 15+ opened modal and no problem. The API let you the possibility to apply a custom background color overlay, so you can also apply a transparent overlay. Do you want me to apply a change into the library?

**Comment by jagabs** [comment]
i think were good. any change i can get ur email or contact so i can show you what i mean? hehe
